### ISSUE TITLE
dependencies-in-metadatajson

### ISSUE THREAD

**Issue by jotacepea** [desalvo/puppet-users#1]
Hi,
When you install "puppet-users" module, the process works fine, but generates a warning message.
This warning message appears when you run a "puppet module list" too.

```
[root@test01 ~]# puppet module list
Warning: Missing dependency 'puppetlabs-stdlib':
  'desalvo-users' (v0.1.0) requires 'puppetlabs-stdlib' (>= 1.0.0)
/etc/puppet/modules
├── desalvo-users (v0.1.0)
├── jfryman-selinux (v0.2.3)
├── puppetboard (???)
├── puppetlabs-apache (v1.4.0)
├── puppetlabs-apt (v1.4.2)
├── puppetlabs-concat (v1.2.0)
├── puppetlabs-firewall (v0.0.4)
├── puppetlabs-haproxy (v0.4.1)
├── puppetlabs-inifile (v1.0.0)
├── puppetlabs-mysql (v0.6.1)
├── puppetlabs-ntp (v3.1.2)
├── puppetlabs-postgresql (v3.4.2)
├── puppetlabs-puppetdb (v3.0.1)
├── puppetlabs-stdlib (v4.5.1)
├── thias-memcached (v0.1.0)
└── thias-php (v1.1.0)
/usr/share/puppet/modules (no modules installed)
[root@test01 ~]# 
```

I am not sure, but I believe it is a problem in metadata.json format, in dependencies section.
The name of the module is "puppetlabs-stdlib", but if you use this "puppetlabs/stdlib", it works fine.
Puppet Doc: https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#dependencies-in-metadatajson

Best,

**Comment by desalvo** [comment]
Thanks, indeed. It's fixed now.
Best,

   Alessandro
